### ISSUE TITLE
NdefLibraryExtension not compatible with UWP

### ISSUE THREAD

**Issue by thang2410199** [andijakl/ndef-nfc#10]
I clonedthe project to try out the demo, but I realize that NdefLibraryExtension in nuget is not compatible with UWP yet. So I try to build to lib, but cant not because of antlr.runtime.dll missing.
I cant get the demo to work.

**Comment by andijakl** [comment]
Did you try building the NdefLibraryUwp? The NdefLibraryWin is for Windows 8.1 and not compatible to WinRT. Make sure you restore all the NuGet references, also from referenced the VcardLibrary.
Please let me know if you can get it to work though that!

**Comment by thang2410199** [comment]
Here is the process I worked through to get the build success:
- Set **NdefLibraryUwp.rd.xml** of **NdefLibraryUwp ** 's build action to **Embedded Resource**
- Build **NdefLibraryUwp**
- In NdefDemoWin10, Add reference to the new build NdefLibraryUwp.dll
- Build NdefDemoWin10

**Comment by andijakl** [comment]
Tested the whole process using another PC than my dev machine - you were right. The actual issue was that the NdefLibraryExtension 3.1.1 was not yet available on the NuGet servers. Seemed like the push didn't go through back then. I've pushed the package to the servers again and it should now work to build the NdefDemoWin10 based on the NFC / NDEF library NuGet packages.
Changing the build action to Embedded Resource should not be required as to my knowledge.
Thanks again for reporting the issue!
