### ISSUE TITLE
Message begin/end check typo

### ISSUE THREAD

**Issue by amis92** [andijakl/ndef-nfc#11]
Was just reading through code when I met a bad condition check. I think there should be `||` operator instead.

>@ https://github.com/andijakl/ndef-nfc/blob/master/NdefLibrary/NdefLibrary/Ndef/NdefMessage.cs#L251

```csharp
if (!seenMessageBegin && !seenMessageEnd) 
{ 
    throw new NdefException(NdefExceptionMessages.ExMessageNoBeginOrEnd); 
} 
```

**Comment by andijakl** [comment]
Checked with the NDEF spec; I think it should be correct - in case of chunked payloads, it's valid that there is no message end bit set in the NDEF message. In that case, it would actually only be the name of the error message resource that's wrong and that should say "And" instead of "Or". Did you check with the NDEF specs?

**Comment by amis92** [comment]
Nah, the resource name mislead me, didn't check specs. :) Invalid then, sorry I bothered you.
